services:
    rpi_imagegen:
        build: .
        privileged: true
        userns_mode: keep-id
        stdin_open: true
        tty: true
        image: rpi-imagegen:latest
        volumes:
            - ./coderbot:/build/coderbot
            - /proc/sys/fs/binfmt_misc:/proc/sys/fs/binfmt_misc  
      
